# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeners',
            old_name='repository_uuid',
            new_name='listener_uuid',
        ),
    ]
