# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeners',
            name='development_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listeners.FTPServers'),
        ),
        migrations.AlterField(
            model_name='listeners',
            name='production_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listeners.FTPServers'),
        ),
    ]
