# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0002_auto_20160119_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeners',
            name='listener_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
