# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0003_listeners_listener_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeners',
            name='listener_url',
        ),
        migrations.AddField(
            model_name='listeners',
            name='repository_url',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
