# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0004_auto_20160119_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeners',
            name='enable_development',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeners',
            name='enable_production',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
