# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0006_auto_20160121_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
